/*
 * MDIO_private.h
 *
 *  Created on: Aug 24, 2026
 *      Author: Anthony Gaius
 */

#ifndef MDIO_PRIVATE_H_
#define MDIO_PRIVATE_H_

#include "../../LIB/STD_TYPES.h"

/* PORTA */
#define PORTA       (*(volatile u8 *)(0x3B))
#define DDRA        (*(volatile u8 *)(0x3A))
#define PINA        (*(volatile u8 *)(0x39))

/* PORTB */
#define PORTB       (*(volatile u8 *)(0x38))
#define DDRB        (*(volatile u8 *)(0x37))
#define PINB        (*(volatile u8 *)(0x36))

/* PORTC */
#define PORTC       (*(volatile u8 *)(0x35))
#define DDRC        (*(volatile u8 *)(0x34))
#define PINC        (*(volatile u8 *)(0x33))

/* PORTD */
#define PORTD       (*(volatile u8 *)(0x32))
#define DDRD        (*(volatile u8 *)(0x31))
#define PIND        (*(volatile u8 *)(0x30))

/* Private Concatenation Macros */
#define PRIVATE_CONC(b7,b6,b5,b4,b3,b2,b1,b0)   PRIVATE_CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)
#define PRIVATE_CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0) 0b##b7##b6##b5##b4##b3##b2##b1##b0

/* Concatenated Directions */
#define DIO_PORTA_DIR  PRIVATE_CONC(DIO_PORTA_PIN7_DIR, DIO_PORTA_PIN6_DIR, DIO_PORTA_PIN5_DIR, DIO_PORTA_PIN4_DIR, DIO_PORTA_PIN3_DIR, DIO_PORTA_PIN2_DIR, DIO_PORTA_PIN1_DIR, DIO_PORTA_PIN0_DIR)
#define DIO_PORTB_DIR  PRIVATE_CONC(DIO_PORTB_PIN7_DIR, DIO_PORTB_PIN6_DIR, DIO_PORTB_PIN5_DIR, DIO_PORTB_PIN4_DIR, DIO_PORTB_PIN3_DIR, DIO_PORTB_PIN2_DIR, DIO_PORTB_PIN1_DIR, DIO_PORTB_PIN0_DIR)
#define DIO_PORTC_DIR  PRIVATE_CONC(DIO_PORTC_PIN7_DIR, DIO_PORTC_PIN6_DIR, DIO_PORTC_PIN5_DIR, DIO_PORTC_PIN4_DIR, DIO_PORTC_PIN3_DIR, DIO_PORTC_PIN2_DIR, DIO_PORTC_PIN1_DIR, DIO_PORTC_PIN0_DIR)
#define DIO_PORTD_DIR  PRIVATE_CONC(DIO_PORTD_PIN7_DIR, DIO_PORTD_PIN6_DIR, DIO_PORTD_PIN5_DIR, DIO_PORTD_PIN4_DIR, DIO_PORTD_PIN3_DIR, DIO_PORTD_PIN2_DIR, DIO_PORTD_PIN1_DIR, DIO_PORTD_PIN0_DIR)

/* Concatenated Values */
#define DIO_PORTA_VAL  PRIVATE_CONC(DIO_PORTA_PIN7_VAL, DIO_PORTA_PIN6_VAL, DIO_PORTA_PIN5_VAL, DIO_PORTA_PIN4_VAL, DIO_PORTA_PIN3_VAL, DIO_PORTA_PIN2_VAL, DIO_PORTA_PIN1_VAL, DIO_PORTA_PIN0_VAL)
#define DIO_PORTB_VAL  PRIVATE_CONC(DIO_PORTB_PIN7_VAL, DIO_PORTB_PIN6_VAL, DIO_PORTB_PIN5_VAL, DIO_PORTB_PIN4_VAL, DIO_PORTB_PIN3_VAL, DIO_PORTB_PIN2_VAL, DIO_PORTB_PIN1_VAL, DIO_PORTB_PIN0_VAL)
#define DIO_PORTC_VAL  PRIVATE_CONC(DIO_PORTC_PIN7_VAL, DIO_PORTC_PIN6_VAL, DIO_PORTC_PIN5_VAL, DIO_PORTC_PIN4_VAL, DIO_PORTC_PIN3_VAL, DIO_PORTC_PIN2_VAL, DIO_PORTC_PIN1_VAL, DIO_PORTC_PIN0_VAL)
#define DIO_PORTD_VAL  PRIVATE_CONC(DIO_PORTD_PIN7_VAL, DIO_PORTD_PIN6_VAL, DIO_PORTD_PIN5_VAL, DIO_PORTD_PIN4_VAL, DIO_PORTD_PIN3_VAL, DIO_PORTD_PIN2_VAL, DIO_PORTD_PIN1_VAL, DIO_PORTD_PIN0_VAL)

#endif /* MDIO_PRIVATE_H_ */
