/*
 * MTIMER_private.h
 *
 *  Created on: Aug 30, 2026
 *      Author: Anthony Gaius
 */

#ifndef MTIMER_PRIVATE_H_
#define MTIMER_PRIVATE_H_

#include "../../CONFIG/TIMER/MTIMER_config.h"

/* TCCR0 bits */
#define MTIMER_TCCR0_WGM00_BIT 0U
#define MTIMER_TCCR0_WGM01_BIT 1U
#define MTIMER_TCCR0_CS00_BIT 0U
#define MTIMER_TCCR0_CS01_BIT 1U
#define MTIMER_TCCR0_CS02_BIT 2U

/* TCCR2 bits */
#define MTIMER_TCCR2_WGM20_BIT 6U
#define MTIMER_TCCR2_WGM21_BIT 3U
#define MTIMER_TCCR2_CS20_BIT 0U
#define MTIMER_TCCR2_CS21_BIT 1U
#define MTIMER_TCCR2_CS22_BIT 2U

/* TIMSK bits */
#define MTIMER_TIMSK_TOIE0_BIT 0U
#define MTIMER_TIMSK_OCIE0_BIT 1U
#define MTIMER_TIMSK_TOIE2_BIT 6U
#define MTIMER_TIMSK_OCIE2_BIT 7U
#define MTIMER_TIMSK_TOIE1_BIT 2U
#define MTIMER_TIMSK_OCIE1A_BIT 3U
#define MTIMER_TIMSK_OCIE1B_BIT 4U

/* TIFR bits */
#define MTIMER_TIFR_OCF1A_BIT 4U

/* Timer0 / Timer2 prescaler clock-select bit patterns */
#if (MTIMER_TIMER0_PRESCALER == MTIMER_PRESCALER_1)
#define MTIMER_PRIVATE_TIMER0_CS_BITS 0x01U
#elif (MTIMER_TIMER0_PRESCALER == MTIMER_PRESCALER_8)
#define MTIMER_PRIVATE_TIMER0_CS_BITS 0x02U
#elif (MTIMER_TIMER0_PRESCALER == MTIMER_PRESCALER_64)
#define MTIMER_PRIVATE_TIMER0_CS_BITS 0x03U
#elif (MTIMER_TIMER0_PRESCALER == MTIMER_PRESCALER_256)
#define MTIMER_PRIVATE_TIMER0_CS_BITS 0x04U
#else
#define MTIMER_PRIVATE_TIMER0_CS_BITS 0x05U
#endif

#if (MTIMER_TIMER2_PRESCALER == MTIMER_PRESCALER_1)
#define MTIMER_PRIVATE_TIMER2_CS_BITS 0x01U
#elif (MTIMER_TIMER2_PRESCALER == MTIMER_PRESCALER_8)
#define MTIMER_PRIVATE_TIMER2_CS_BITS 0x02U
#elif (MTIMER_TIMER2_PRESCALER == MTIMER_PRESCALER_64)
#define MTIMER_PRIVATE_TIMER2_CS_BITS 0x03U
#elif (MTIMER_TIMER2_PRESCALER == MTIMER_PRESCALER_256)
#define MTIMER_PRIVATE_TIMER2_CS_BITS 0x04U
#else
#define MTIMER_PRIVATE_TIMER2_CS_BITS 0x05U
#endif

/* Timer1 prescaler clock-select bit patterns (TCCR1B CS12:0) */
#if (MTIMER_TIMER1_PRESCALER == MTIMER1_PRESCALER_1)
#define MTIMER_PRIVATE_TIMER1_CS_BITS 0x01U
#elif (MTIMER_TIMER1_PRESCALER == MTIMER1_PRESCALER_8)
#define MTIMER_PRIVATE_TIMER1_CS_BITS 0x02U
#elif (MTIMER_TIMER1_PRESCALER == MTIMER1_PRESCALER_64)
#define MTIMER_PRIVATE_TIMER1_CS_BITS 0x03U
#elif (MTIMER_TIMER1_PRESCALER == MTIMER1_PRESCALER_256)
#define MTIMER_PRIVATE_TIMER1_CS_BITS 0x04U
#else
#define MTIMER_PRIVATE_TIMER1_CS_BITS 0x05U
#endif

/* Timer0 mode bit patterns (WGM01:00) */
#if (MTIMER_TIMER0_MODE == MTIMER_MODE_CTC)
#define MTIMER_PRIVATE_TIMER0_MODE_BITS (1U << MTIMER_TCCR0_WGM01_BIT)
#else
#define MTIMER_PRIVATE_TIMER0_MODE_BITS 0x00U
#endif

/* Timer2 mode bit patterns (WGM21:20) */
#if (MTIMER_TIMER2_MODE == MTIMER_MODE_CTC)
#define MTIMER_PRIVATE_TIMER2_MODE_BITS (1U << MTIMER_TCCR2_WGM21_BIT)
#elif (MTIMER_TIMER2_MODE == MTIMER_MODE_FAST_PWM)
#define MTIMER_PRIVATE_TIMER2_MODE_BITS \
  ((1U << MTIMER_TCCR2_WGM21_BIT) | (1U << MTIMER_TCCR2_WGM20_BIT))
#else
#define MTIMER_PRIVATE_TIMER2_MODE_BITS 0x00U
#endif

/* Timer1 mode bit patterns (WGM13:10 in TCCR1A/B) */
#if (MTIMER_TIMER1_MODE == MTIMER_MODE_CTC)
#define MTIMER_PRIVATE_TIMER1_MODE_BITS 0x08U /* WGM12=1 */
#else
#define MTIMER_PRIVATE_TIMER1_MODE_BITS 0x00U
#endif

#endif /* MTIMER_PRIVATE_H_ */
